"""
Base strategy definitions and data classes.
"""
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class StrategySignal:
    """Represents a trading signal generated by a strategy."""

    has_signal: bool
    symbol: str = ""
    side: str = "LONG"
    entry: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    risk_reward: float = 0.0
    strategy_id: str = ""
    reason: list[str] = field(default_factory=list)
    score: float = 0.0
    grade: str = ""
    warnings: list[str] = field(default_factory=list)
    metrics: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert to a dictionary for Firestore storage."""
        return {
            "symbol": self.symbol,
            "side": self.side,
            "status": "CREATED",
            "entry": self.entry,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": self.risk_reward,
            "strategy_id": self.strategy_id,
            "reason": self.reason,
            "score": self.score,
            "grade": self.grade,
            "warnings": self.warnings,
            "metrics": self.metrics,
            "timeframe_context": {
                "trend": "1d",
                "entry": "4h",
            },
        }
